### ISSUE TITLE
Generate a seperate PNG file per Script file.

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSClassUtils#69]
Example was submitted by dough finke in this PR:
https://github.com/Stephanevg/PSClassUtils/pull/8

**Comment by LxLeChat** [comment]
Okso i think we will have to rewrite the function, and maybe add a new switch parameter.

For Example, we should use $PSBoundParameters['Parameter'] instead of the variable name for a better reading of the script.

I'll do it if you want.
Add the task to a project, or maybe we can create a new project called "Enhancement" ?

**Comment by Stephanevg** [comment]
Closed as this has been resolved in merge above
